# version: '3.8'

# services:
#   airflow:
#     image: airflow:local
#     build:
#       context: ./
#       dockerfile: Dockerfile.airflow
#       args:
#         AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
#         AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
#         AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
#     container_name: airflow
#     env_file:                       
#       - .env
#     environment:
#       - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs availabl
#       - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=1000
#       - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True
#     ports:
#       - "8080:8080"



version: '3.8'

services:
  airflow:
    image: airflow:local
    build:
      context: ./
      dockerfile: Dockerfile.airflow
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    container_name: airflow
    env_file:                       
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Make all GPUs availabl
      - AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT=1000
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=True

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    runtime: nvidia
    ports:
      - "8080:8080"

